"""add template_version and naming_convention to generated_code_files

Revision ID: a5085e2e12f5
Revises: 
Create Date: 2026-06-12 10:55:24.868729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5085e2e12f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_code_files', sa.Column('template_version', sa.String(length=20), nullable=True))
    op.add_column('generated_code_files', sa.Column('naming_convention', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_code_files', 'naming_convention')
    op.drop_column('generated_code_files', 'template_version')
    # ### end Alembic commands ###
